apiVersion: v2
appVersion: v0.5.7-truvity.8
description: A Kubernetes webhook for pods that need AWS IAM access (Truvity fork with admission/v1 support)
home: https://github.com/truvity/amazon-eks-pod-identity-webhook
keywords:
- aws
- iam
- eks
- irsa
- iam-roles-for-service-accounts
- eks-pod-identity-webhook
- aws-pod-identity-webhook
maintainers:
- name: truvity
  url: https://github.com/truvity
name: amazon-eks-pod-identity-webhook
sources:
- https://github.com/truvity/amazon-eks-pod-identity-webhook
- https://github.com/aws/amazon-eks-pod-identity-webhook/
- https://github.com/jkroepke/helm-charts/tree/main/charts/amazon-eks-pod-identity-webhook
type: application
version: 0.5.7-truvity.8
